### ISSUE TITLE
Gem should declare dependency on actionmailbox or set it as optional

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [mailpace/mailpace-rails#27]
Hi!
Just wanted to let you know that the gem should declare a dependency on actionmailbox, my rails installation doesn't use actionmailbox and activestorage and as such, are disabled.
In development, this goes unnoticed (due to lazy load), however in production this caused a small outage because activestorage couldn't be loaded

**Comment by paul-oms** [comment]
Thanks for the feedback and apologies for the delay in getting back (notifications on this repo were disabled).

Apologies for causing an outage, I know how annoying that can be. This is now fixed in https://github.com/mailpace/mailpace-rails/commit/a8a15d0156ab9c70dadec56b5bf846853e4018a2 and will be in the next version
